### ISSUE TITLE
WaypointMissionExecuteState stuck in UNKNOWN

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#56]
SDK: `5.1` and `5.1.1`
Drone: Mavic 3 Enterprise

I am using the `WaypointMissionManager`. I have implemented both `addWaypointMissionExecuteStateListener` and `addWaylineExecutingInfoListener`. When attempting to utilize the data these callbacks return, they will sometimes never fire even though I am uploading/starting/stopping a waypoint mission. Everytime this happens, the `WaypointMissionExecuteState` is always `UNKNOWN` and I have not seen a way to get it out of that state.

Here is my code for just the `WaypointMissionExecuteStateListener`.

```
fun initMonitor() {
    waypointMissionManager.clearAllWaypointMissionExecuteStateListener()
    waypointMissionManager.addWaypointMissionExecuteStateListener { state ->
        Log.e("WaypointMission", "Waypoint State: ${state.name}")
    }
}
```

I start/stop/upload the waypoint mission in separate functions. Is there an initializing problem I'm doing? Or is the problem elsewhere? I've experienced this on more then 50% of the waypoint missions I test. The waypoint missions themselves always execute correctly.

**Comment by DJI-William** [comment]
A known issue for us is. If you open the DJI Pilot 2 already and open an MSDK app. Even though you forcely stop the DJI Pilot 2, there are many functions are malfunction in MSDK app such as no callback in addWaylineExecutingInfoListener and WaypointMissionExecuteState always stuck in a state. We have already report this bug to the dev team. Make sure you do the following things.
1. Kill every app first or forcely stop all apps.
2. Just open your MSDK app.
Note*: Make sure you forcely stop an app before opening another one.

**Comment by tkocik92** [comment]
Is there a rough idea of when this will be resolved?

~~I followed all of your instructions as followed:~~
~~1. Power on the RC Pro Plus~~
~~2. Disable + Force Stop DJI Pilot 2~~
~~3. Turn on Mavic 3E.~~
~~4. Launch my MSDK app. Log reports `WaypointMissionExecuteState` as `UNKNOWN`.~~
~~5. Uninstall my MSDK app. Re-install. Same log.~~

~~I've tried multiple flows to get the log to report anything other than `UNKNOWN`. No luck.~~

Edit: Apparently connecting to the simulator was the heart of my strike-through problems. The original question still stands.

**Comment by DJI-William** [comment]
So you tried my steps and the issue is still here? Actually it never comes up when I was testing. What happens if you test in our Sample?

**Comment by tkocik92** [comment]
It worked in your sample app. Which led to me re-evaluating what I did wrong and I found something bizarre: my `waypointMissionManager` instance variable was the problem.

I would initialize `waypointMissionManager` as soon as `SDKManagerCallback.onRegisterSuccess` was called (handled elsewhere). It appears that `WaypointMissionManager.getInstance()` does not return the same instance every time. By removing the instance variable and starting the listeners manually, I was able to get out of the `UNKNOWN` state.

My question now is, when is it acceptable to call `WaypointMissionManager.getInstance()`? Is it after the drone is connected? Or should I be able to do it as soon as the app successfully registers (which is the cause of the problem currently)?

**Comment by DJI-William** [comment]
You need to know that once the onRegisterSuccess, it does not mean all aircraft components are initialised properly. You will find the KeyConnection of each compoents such as Gimbal and Camera turns from null to true in a short period of time. In our DJI Pilot 2 and our Sample, you will find the waypointMission is a seperate activity to the register activity. Since they are in different pages, it guarantees that all components including the waypointMissionManager is initialised properly. I would suggest you get the instance of the waypointMissionManager like 500ms delay after the registeration. Also you need to check if the instance is null, if it is, get it again until you get a real instance.

**Comment by tkocik92** [comment]
`WaypointMissionManager.getInstance()` never returned null for me if when called in `SDKManagerCallback.onRegisterSuccess` so unfortunately I can't use that.

Occasionally, the waypoint mission state gets stuck in `UNKNOWN` before or after a successful waypoint mission. I don't have reproduction steps, but the only solution is to power-cycle the remote controller. If I ever figure out reproduction steps, I'll add them.

Edit: I've discovered that manually calling `WaypointMissionManager.getInstance().init()` appears to resolve even more of the occurrences. It seems like it's failing to be called internally sometimes.

**Comment by DJI-William** [comment]
We will investigate further and try to solve this issue in 2 weeks. There will be a 5.2.0 version released in 2 weeks.

**Comment by pavel-vhive** [comment]
I have the same issue, any workaround?

**Comment by tkocik92** [comment]
@pavel-vhive The workaround I described (calling `WaypointMissionManager.getInstance().init()`) works as long as you call it after some unspecified amount of time. In my implementation, the user has to enter a certain screen (not the launch screen) before flying an automated flight so I call it there.

If your app is single screen, you'll have to try calling it on some delayed timer (probably 1-5 seconds).

Or wait until `5.2` is released since it is supposed to come out this week and hope it fixes the issue.

**Comment by pavel-vhive** [comment]
Hi, thank you the reply, unfortunately delaying  WaypointMissionManager.getInstance().init() for 5 seconds did not resolve it.
After 5 seconds I called init() and state became UNKNOWN. I noticed that after power off/on both drone and RC it works almost every time.

**Comment by DJI-William** [comment]
Fixed in 5.2.0, it is planned to be release on this Friday.

**Comment by tkocik92** [comment]
This issue still exists in 5.2.0 with a major difference.

With the Mavic 3E, the first time I fly a waypoint mission, the `WaypointMissionExecuteStateListener` is stuck in `UNKNOWN`. Any flights after landing this first flight do not have this problem.

If I fly the Mavic 3E with a simulator, the `WaypointMissionExecuteStateListener` always works.

The workaround for real flights, again, is to add `WaypointMissionManager.getInstance().init()` prior to the first flight.

**Comment by DJI-William** [comment]
@tkocik92 That is odd. The simulator has no difference comparing to the real world for the WaypointMissionExecuteStateListener. We will call WaypointMissionManager.getInstance().init() for you once your SDK has registered so it must be not the problem. Are you able to record a video for me to show me how to reproduce it by using our Sample's waypoint demo?

**Comment by tkocik92** [comment]
The sample app doesn't have the problem.

The problem came about because I created an instance variable (`val waypointMissionManager = WaypointMissionManager.getInstance()`) and used that instance variable to register the listeners. This does not work as it appears `WaypointMissionManager.getInstance()` does not return the same `WaypointMissionManager` every time.

I'm not sure if this is by design or otherwise, but it is what's currently occurring.

**Comment by DJI-William** [comment]
getInstance is a static variable, it will always return you the same object because it is a single static object.

**Comment by iwashi1t** [comment]
I’m using the DJI Mini4 Pro and encountered a similar issue where the status always stays as UNKNOWN.

In my case, it works if I call `addWaypointMissionExecuteStateListener` at the moment when `FlightControllerKey.KeyConnection` becomes true by listening to it.
